### ISSUE TITLE
A little logic issue?

### ISSUE THREAD

**Issue by caracare521** [EvolveLabs/electron-updater#12]
First here to say, good job, bro. this is what we were considering months ago.

I've played this for a well, and found a little bug maybe, if it is not intended.

It lies in update.js:  
![n fc6 mkq27a iui bb](https://cloud.githubusercontent.com/assets/7552623/9077083/a0422ea2-3b5c-11e5-896f-c2b328c25103.png)

According to this logger:
[05/08/2015:10:25:06:394:log:14772]  after push deps are: { context: 
   { name: 'electron-updater-play-1',
     version: '1.1.0',
     publisher: 'electron-updater-play-1',
     channel: 'latest',
     dev: true,
     updatePending: false,
     updateInProgress: true,
     registry: 'https://registry.npmjs.org',
     appDir: 'f:\\EolderInUse',
     dependencies: { 'electron-updater': '^0.0.x', 'electron-plugins': '^0.0.x' },
     plugins: { 'electron-updater-sample-plugin': '^0.0.2' } },

dev is set to true. So it cannot pass the if logic highlighted in the picture above.

What I guess is that you might submit a dev version by mistake.

**Comment by justinmchase** [comment]
I would be interested in hearing more about your scenario and what you expect to happen here. 

What it's doing here, is to set `dev=true` if it detects a `.git` folder in the same repo as the app. Then if you attempt to update the app, it will not update the app itself. The idea is that in a "dev" environment you would use git and npm to update your app. 

For example, you clone an app then run `elup update`. What it would do would be to replace your local code with whatever is latest in npm. This probably isn't want you're wanting, so it skips updating the app and dependencies. It will still, however, update plugins unless they're linked.

Simply checking for a `.git` folder to detect dev mode is pretty naieve though, I would be interested in hearing your opinion on how to detect that better.

**Comment by caracare521** [comment]
Sounds good, thank you for your quick reply, XD

I guess I misuse your code, my bad.
I just cloned this repo, created a new file, then published it onto npm. 
Then try to update an older version to the latest. Surely there is a .git  folder. 
But yeah, we won't put a .git folder in our published app.

Will keep watching this repo,  XD

**Comment by justinmchase** [comment]
Here is an example electron app you can run:
https://github.com/evolvelabs/electron-updater-sample

If you deploy it via `gulp` then run the deployed app you'll see the full update happen.

**Comment by caracare521** [comment]
Electron-updater-sample is what I was playing. able to update js files in the folder after I commented that dev logic. Will try to deploy first next step. Thank you for the info~
