### ISSUE TITLE
Not enough information in README

### ISSUE THREAD

**Issue by Brankub** [EvolveLabs/electron-updater#20]
Hi, @justinmchase.
You are doing a great work. I tried to use electron-update, but can't figure out:
1. Where updater get URL of update API for Application.
2. How response should looks like?
3. If I have a new version for Application, what should contain file which updater will download. I mean what files?

Thanks in advance!

**Comment by justinmchase** [comment]
Ah sorry, I will try to be more clear in the README. But the updater uses npm to get updates. By default that would be http://npmjs.org, however you can host your own npm server (e.g. [sinopia](https://npmjs.org/packages/sinopia)) and point your application at that server by configuring it in a [.npmrc file](https://docs.npmjs.com/files/npmrc).

It uses a very small subset of the npm api, you can look at sinopia for details on how to mimick that api if you want to build your own. 

For #3, you just publish to npm like normal:
```
$ npm pack
$ npm pub
```

The client app should see the newer version next time it checks and it will do the update at that point.

**Comment by justinmchase** [comment]
I just updated the README:
https://github.com/EvolveLabs/electron-updater

Please let me know if that helps and if there is anything else I can elaborate on.

**Comment by Brankub** [comment]
Nice, that's more than enough! Thank you!

**Comment by caracare521** [comment]
You can host a private npm using cnpm as well,  it works out pretty well for my app.
