### ISSUE TITLE
Unclear on how to update electron binary

### ISSUE THREAD

**Issue by leshow** [EvolveLabs/electron-updater#21]
I'm sorry if this is just me not fully understanding your project, but let me try and clarify things for myself if I can.

I've included electron-updater in my project, and I have sinopia running locally. I have all my js/html/css in a build/ dir (along with the app package.json). I have added `registry: http://localhost:4873` to my package.json. 

I imagine that updates work like this; I pack and publish a new version of my build/ dir. The running app automatically downloads (does electron-updater handle the downloading) the new js/html/css and I can handle the update event in main.js to restart with the new application code. Am I correct so far?

**1:** That's all fine for replacing the app code if I push a new version, but what about when electron-prebuilt gets updated? How does it replace the electron binary? In packaged applications the electron binary is branded for your application so I'm not really sure how this would work. 

**2:** I see you can add a `binaries:` into the package.json but I'm still not sure the sequence of events I would do. 

**3:** I can currently use electron-packager to get a branded release of my code, would I run that, then npm pack and npm publish the archive containing the executable and all of the subfolders?

**4:** what are the scenarios where you get "update available" vs "update required"? Im in a situation where I published my app with a certain version number, then edited the package.json to be lower and sometimes I'll run the app and it gets an update required and restarts with the new code, whereas other times I won't get the spinner at all and just an "update available" log. It seems to alternate between the two; I expected the behaviour to always update on app start.

**5:** is there an example project with electron-updater implemented?

Sorry for asking to many questions at once. I've edited this several times to try and clean it up.

**Comment by leshow** [comment]
An additional comment, the structure of my code is currently like so:

app/
  main.js
  app.html
  app.js
  app.css
  package.json
build/
node_modules/
releases/
tasks/
package.json


the package.json under app/ is my actual application, it doesn't contain electron-prebuilt as a dependency. Whereas the packge.json in the base folder contains dependencies for running gulp tasks and for starting the application (**electron-prebuilt** lives here, gulp, babel, etc)

**Comment by justinmchase** [comment]
@leshow 

> "Am I correct so far?"
I think I understand you, and yes that does sound correct.

1) I've been scrambling to get my own app working so I haven't documented it yet but I know exactly what you're saying and it does handle this case. I will try to update the wiki and the sample app as soon as I can but I'll try to explain it briefly right now as well.

A) We are using grunt to copy our entire application + `node_modules/electron-updater` into `release/app`. 
B) We then use [electron-packager](https://npmjs.org/packages/electron-packager), which combines the binaries from an electron drop, our app and does the branding.
C) We then generate a tgz containing the branded electron files, minus our application code.
D) We deploy the branded electron binaries (tgz) to an aws bucket.
E) You add this to your applications package.json: 
```
  "binaries": [],
  "electronBinaries": [
    "https://s3.amazonaws.com/evolve-bin/{name}/electron-v0.31.0-{platform}-{arch}.tgz"
  ]
```
2) The `electronBinaries` are handled slightly differently than `binaries`. Binaries are extracted as is into the packages root, they can be in plugins or in the application. Electron binaries are extracted verbatim into the electron application directory (different between mac and windows for example) and are only respected when in the application package itself. 

When your application package is updated it also updates `electronBinaries`.

3) You still `npm pack` from your application root directory, you don't need to bundle anything with this package. We then use [electron-builder](https://npmjs.org/packages/electron-builder) to generate an installer/dmg which bundles electron, our app and the updater (e.g. the results of electron-packager). This installer has what it needs to bootstrap itself and perform an update on first usage.

4) When the app first launches it looks through the dependencies and attempts to see if it has what it needs to launch. If any dependency is missing then an update is required. So for example, if an entire plugin is not found the app can't run at all without it so an update is required before the app can run. However if the app has all of depedencies and plugins matching the versions in the package.json's then it will go ahead and let the app load as is. It will then reach out to the server and see if there are any newer version matching the version ranges specified. If a newer version is available then it will emit an update available event. If the updates are only plugins then simply restarting the app will apply the new versions, since they are installed side-by-side. If the application itself changes then when the application is restarted it will go into full-update mode, patching the entire application and then restart as the new version.

5) There is this project but I need to fix it up probably:
https://github.com/EvolveLabs/electron-updater-sample

The main app I'm working on is closed source at the moment, we're working hard to get something shippable. We are releasing updates for our app internally at the moment. I will take a look at the updater sample app soon and see what needs to be changed on it. This is a relatively new project and its important for it to be as high quality and stable as possible so we really appreciate any scrutiny or feedback you have. 

Here are some files from the real project that I should document in the wiki and/or add into the updater sample app, that you can reference for now:

## gulp.js
```
var gulp = require('gulp'),
    rename = require('gulp-rename'),
    electron = require('electron-prebuilt'),
    path = require('path')

var releaseDir = 'release'
var releaseAppDir = path.join(releaseDir, 'app')

gulp.task('copy-styles', function () {
    return gulp
        .src('styles/**/*')
        .pipe(gulp.dest(path.join(releaseAppDir, 'styles')))
})

gulp.task('copy-res', function () {
    return gulp
        .src('res/**/*')
        .pipe(gulp.dest(path.join(releaseAppDir, 'res')))
})

gulp.task('copy-app', function () {
    return gulp
        .src('app/**/*')
        .pipe(gulp.dest(path.join(releaseAppDir, 'app')))
})

gulp.task('copy-electron-updater', function () {
    return gulp
        .src('node_modules/electron-updater/**/*')
        .pipe(gulp.dest(path.join(releaseAppDir, 'node_modules', 'electron-updater')))
})

gulp.task('copy-npmrc', function () {
    return gulp
        .src('.npmrc')
        .pipe(gulp.dest(releaseAppDir))
})

gulp.task('copy-all', ['copy-styles', 'copy-res', 'copy-app', 'copy-electron-updater', 'copy-npmrc'], function () {
    var appFiles = [
        'evolve.html',
        'evolve.js',
        'main.js',
        'package.json'
    ]
    return gulp
        .src(appFiles)
        .pipe(gulp.dest(releaseAppDir))
})
 
gulp.task('release', ['copy-all'])
gulp.task('default', ['release'])
```

## build.sh
```
#!/bin/bash

# build steps
clean_step=false
gulp_step=false
pack_step=false
build_step=false

# build platforms
build_win32=false
build_linux=false
build_darwin=false

# other
build_arch="x64"
electron_version="0.30.4"
app_name="Evolve V2 Beta"
bin_dir="./node_modules/.bin"

# Step Functions

function step.clean {
	if [ -d "./release" ]; then
		# Cross platform deletion of long file paths.
		$bin_dir/wnddel "./release"
		if [ $? -ne 0 ]; then
			echo "Failed to clean. Be sure to 'npm update' to get wnddel."
			exit 1
		fi
	fi
	echo "Cleaned."
}

function step.gulp {	
	gulp
	if [ $? -ne 0 ]; then
		echo "Failed to clean"
		exit 1
	fi
}
 
function step.pack {	
	if [ $build_linux = true ]; then
		echo "Linux packaging not yet supported."
		exit 1
	fi
	if [ $build_win32 = true ]; then
		${bin_dir}/electron-packager ./release/app "${app_name}" --platform=win32 --arch=$build_arch --version=$ELECTRON_VERSION --out=./release/win32 --icon=assets/win32/evolve.ico
		if [ $? -ne 0 ]; then
			echo "Packaging failed."
			exit 1
		fi

		if [ -d "release/win32/${app_name}-win32" ]; then
			# A bug in electron packager inconsistently names app directory on different platforms.
			mv "release/win32/${app_name}-win32" "release/win32/${app_name}-win32-${build_arch}"
			if [ $? -ne 0 ]; then
				exit 1
			fi
		fi
	fi
	if [ $build_darwin = true ]; then
		${bin_dir}/electron-packager ./release/app "${app_name}" --platform=darwin --arch=$build_arch --version=$ELECTRON_VERSION --out=./release/darwin --icon=assets/macos/evolve.icns
		if [ $? -ne 0 ]; then
			echo "Packaging failed."
			exit 1
		fi

		if [ -d "release/darwin/${app_name}.app" ]; then
			# A bug in the electron-packager can result in the folder being named differently sometimes.
			mkdir "release/darwin/${app_name}-darwin-${build_arch}"
			mv "release/darwin/${app_name}.app" "release/darwin/${app_name}-darwin-${build_arch}/${app_name}.app"
			if [ $? -ne 0 ]; then
				exit 1
			fi
		fi
	fi
}

function step.build {
	if [ $build_linux = true ]; then
		echo "Linux build not yet supported."
		exit 1
	fi
	if [ $build_win32 = true ]; then

		# Package electron binaries for deployment
		pushd "./release/win32/${app_name}-win32-${build_arch}" > /dev/null
		tar czvf "../electron-v${ELECTRON_VERSION}-win32-${build_arch}.tgz" --exclude './resources/app/*' --exclude 'resources/app' *
		if [ $? -ne 0 ]; then
			exit 1
		fi
		popd > /dev/null

		# Create app installer
		${bin_dir}/electron-builder "./release/win32/${app_name}-win32-${build_arch}" --platform=win32 --config=setup-config.json --out=./release/win32
		if [ $? -ne 0 ]; then
			exit 1
		fi

		mv "./release/win32/$app_name Setup.exe" "./release/win32/Evolve-V2-installer-x64.exe"
		if [ $? -ne 0 ]; then
			exit 1
		fi
	fi
	if [ $build_darwin = true ]; then

		darwin_app=./release/darwin/${app_name}-darwin-${build_arch}/${app_name}.app

		# Package electron binaries for deployment
		pushd "${darwin_app}" > /dev/null
		tar czvf "../../electron-v${ELECTRON_VERSION}-darwin-${build_arch}.tgz" --exclude 'Contents/Resources/app/*' --exclude 'Contents/Resources/app' *
		if [ $? -ne 0 ]; then
			exit 1
		fi
		popd > /dev/null

		${bin_dir}/electron-builder "${darwin_app}" --platform=osx --config=setup-config.json --out=./release/darwin
		if [ $? -ne 0 ]; then
			exit 1
		fi
	fi
}


# Process arguements, and defaults
while [[ $# > 0 ]]
do
key="$1"
case $key in
	# clean
	-c|--clean|clean)
	clean_step=true
	;;

	# gulp
	-g|--gulp|gulp)
	gulp_step=true
	;;

	# pack
	-p|--pack|pack)
	pack_step=true
	;;

	# build
	-b|--build|build)
	build_step=true
	;;

    # win32
    -w|--win32|win32)
    build_win32=true
    ;;

    # linux
    -l|--linux|linux)
    build_linux=true
    ;;

    # darwin
    -d|--darwin|darwin)
    build_darwin=true
    ;;

    # arch
    -x86|x86|-ia32|ia32)
    build_arch="ia32"
    ;;
    -x64|x64)
    build_arch="x64"
    ;;

    # electron version
    -e|--electron)
	ELECTRON_VERSION="$2"
	shift
	;;

	-n|--name)
	app_name="$2"
	shift
	;;

    # unknown option
    *) 
    echo "Unknown option: $i"
    exit 1
    ;;
esac
shift
done

# Electron version defaults.
if [ ! $ELECTRON_VERSION ]; then
    # otherwise, attempt to get the current latest version of electron from github
    ELECTRON_VERSION=`curl https://github.com/atom/electron/releases/latest -Is | grep 'Location: ' | cut -f2- -d' '`
    ELECTRON_VERSION=`basename $ELECTRON_VERSION | cut -f2- -d'v' | tr -d '\r'`
fi

plat=`uname`
# Build platform defaults
if [ $build_win32 = false ] && [ $build_darwin = false ] && [ $build_linux = false ]; then
	# build_linux=true # not yet supported
	build_darwin=true
	build_win32=true
fi

# Platform specific settings
if [ $plat == 'Darwin' ]; then
	# darwin only supports x64
	build_arch="x64"
elif [ $plat == 'Linux' ]; then
	# Linux specific stuff here.
	echo ''
else
	# windows cannot build darwin
	build_darwin=false
fi

# Execute steps
if [ $clean_step = true ] || [ $gulp_step = true ] || [ $pack_step = true ] || [ $build_step = true ]; then
	# if any are specified build each step specified.
	if [ $clean_step = true ]; then
		step.clean
	fi
	if [ $gulp_step = true ]; then
		step.gulp
	fi
	if [ $pack_step = true ]; then
		step.pack
	fi
	if [ $build_step = true ]; then
		step.build
	fi
else
	# if none are specified then do a full release build
	step.clean
	step.gulp
	step.pack
	step.build

	# do not publish automatically, manual step required.
	echo "Electron binaries are ready to be published."
fi
```

**Comment by leshow** [comment]
holy! thanks for such a detailed comment. I'm going to spend some time doing some testing and reading through this properly. thank you for your help.

**Comment by justinmchase** [comment]
I should probably move that script into the `electron-updater-tools` project... the electron version getter isn't quite right here either. 

We are also using travisci.org and appveyor.com to generate and deploy binaries to amazon. Here is an example project with native addons we are using in a plugin:
https://github.com/EvolveLabs/electron-ref

**Comment by leshow** [comment]
Thank you.

A few follow up questions:

1. you generate a tgz of the results from electron-packager **minus** the app dir. do you `npm pub` the tgz that is the result of that to your sinopia service? or do you just upload the tgz to your aws instance and set the electronBinaries field? (I suppose you'd add the field to `package.json` in the first step not the last
2. `. If the application itself changes then when the application is restarted it will go into full-update mode, patching the entire application and then restart as the new version.`
When the app hits an `update required` on startup I can see it the spinner come up and the application code get replaced, but I don't see in the README how to trigger the download/apply the update programatically. What do I put inside the update-available callback for example to download and apply the available update?

Still reading through and testing a few things, You can close this issue if you want but if you don't mind I may still ask some additional questions. Thanks so much for your time.

**Comment by justinmchase** [comment]
1) I npm pack from the app dir, upload the tgz (which only changes when we adopt a new version of electron). Something like this:

```
$ npm version minor -m 'Added feature xyz'
$ build # on mac, creates installers and branded electron tgz
```
* Upload `release/win32/electron-v0-31.0-win32-x64.tgz` to aws, if it changed from last time
* Upload `release/win32/Evolve-V2-installer-x64.exe` to aws as the new "default" download installer.
```
$ npm pack # from same directory as build
$ npm pub
```

2) All that has to happen is for the app to be restarted. I haven't actually added an api in there to do it automatically yet. Right now we're just telling the users to do it manually via the event notification. But  it would basically be like this:
```
                var spawn = require('child_process').spawn;
                var child = spawn(process.execPath, process.argv, {
			detached: true,
			cwd: process.cwd(),
			stdio: ['ignore', 'ignore', 'ignore']
		})
		child.unref();
                process.exit(0);
```
I'll open an issue and work on it.

**Comment by justinmchase** [comment]
#22

**Comment by leshow** [comment]
I'm going to close this issue since you've addressed all of my questions, I've got app code updating right now, about to try the electronBinaries update process. Thanks again.

**Comment by jaunkst** [comment]
Just to clarify for anyone else, @justinmchase  is referring to the a private npm repository when he refers to uploading to amazon.

**Comment by justinmchase** [comment]
@jaunkst The node packages do get uploaded to npm (or your ec2 hosted sinopia instances) but the tgz's with your pre-built binaries get uploded to aws, which can be done from a travis ci build.

**Comment by jaunkst** [comment]
okay so i will need to pack the binary up and put it up on s3. Is this the complete binary or with the app removed.

npm-repo <- app
s3 <- branded binary - app

is this correct?

**Comment by justinmchase** [comment]
Yes :)

The (optional) `electron-v0-31.0-${platform}-x64.tgz` binary should have all of electron, including the branded binaries, excluding your app files, which go into npm. Your `.app` file or your windows installer  has everything in it.

When it goes to update it will update the app from npm, which may have a new version of electron in the `"electronBinaries"` section of `package.json` which would then be downloaded from amazon.

**Comment by jaunkst** [comment]
@justinmchase thanks for the clarification. I will give this a go tomorrow morning.
