### ISSUE TITLE
Missing package.json key leads to errors

### ISSUE THREAD

**Issue by youanden** [EvolveLabs/electron-updater#31]
Excluding the `"plugins": {}` key/value from the `package.json` yields a non-helpful error:

`Cannot convert undefined or null to object`

Please either catch such a situation with a better error or add instructions to the documentation.

**Comment by justinmchase** [comment]
It should not throw in that case, thanks for reporting.

**Comment by justinmchase** [comment]
This was actually a bug in the `electron-plugins` package. Fixed in `v0.0.4` of that package.
