### ISSUE TITLE
Random Error from appendToConsole in Logger

### ISSUE THREAD

**Issue by aaronfrost** [EvolveLabs/electron-updater#37]
I randomly get an error that bubbles to the user. It is in lib/Logger.js. In `appendToConsole`, it attempts to write something to the console. I would love to wrap this in a try/catch so that it doesn't bubble to the user. If I PR this, would you accept?

![screen shot 2015-12-05 at 10 13 17 pm](https://cloud.githubusercontent.com/assets/662832/11611802/709b1186-9b9d-11e5-949c-459b43af1550.png)

**Comment by justinmchase** [comment]
Yes, this definitely shouldn't bubble up. It sounds like the process is closing when the logger is trying to write, I would definitely try catch on this.

**Comment by aaronfrost** [comment]
PR coming soon. Thanks @justinmchase!

**Comment by aaronfrost** [comment]
What should I do in the catch? Normally I would log an error or something, but in this case, the console is not available. So... not sure WTF to do. Thoughts?

**Comment by aaronfrost** [comment]
PR Submitted. Let me know if you want a change.

**Comment by justinmchase** [comment]
Fixed bye #38, thanks.
