### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by havenchyk** [EvolveLabs/electron-updater#40]
I'm sorry, but I didn't get the main purpose of this package from the readme file.

Could you please clarify, is this package for making updates of the app itself? Is it provides same as described here https://github.com/atom/electron/blob/master/docs/api/auto-updater.md

**Comment by justinmchase** [comment]
Yes for the app itself, its dependencies, plugins.

Yes it basically provides the same as the built-in electron auto-updater except with some differences (of course).

The primary difference being that there is a single api for all three platforms: darwin, linux, win32; And they all behave the same way. It's all javascript and there is no need for platform specific tools or build processes. The distribution system is npm, via packages. Simply publishing to npm is how you distribute updates to your app.

**Comment by justinmchase** [comment]
Closing this for now, feel free to re-open if you have more questions.

**Comment by havenchyk** [comment]
Sure, thanks!
