### ISSUE TITLE
Support for different npm package name

### ISSUE THREAD

**Issue by bhanuc** [EvolveLabs/electron-updater#52]
Currently the updater uses the application name to get the updates but since a library is already registered under my application's name, I wish to push my application under a different package name instead of managing a private npm server. I can do a PR as I think only few changes are to be made in index.js, lib/check.js and command.js are required it seems.

**Comment by justinmchase** [comment]
You're going to have to change the name then, in that case. You can consider getting [private npm](https://www.npmjs.com/private-modules) which will allow you to add a scope to the name.

**Comment by bhanuc** [comment]
I see a simple solution to add a url in the package.json file or add it in the function definition, if defined the new values would be used in constructing the url in update.js and check.js files else the default code would run. Would you guys be open to this small addition.

**Comment by justinmchase** [comment]
I don't understand the purpose though. You would still have to have a uniquely named project in order to upload it to npm. If you have a uniquely named project then it will already work. 

You can override a package who's name is already taken by using your own private npm though.
