### ISSUE TITLE
Does electron-updater work for portable app?

### ISSUE THREAD

**Issue by ardoramor** [EvolveLabs/electron-updater#57]
I've just started to explore electron app auto-updates. My project currently has a requirement to be portable. That is, it shouldn't be installed onto the user's machine. The auto-updater directly supported by Atom Electron is tied to Squirrel installer so that doesn't work for me. I wanted to see if electron-updater can work.

I produce a release the same way you would prepare a release for installation but without packaging it into installation. That is, copy of electron runtime, .asar archives and a few other files are in the folder along with package.json.

I've applied the electron-updater bootstrap to the electron application as well as an ipc listener to the render thread.

My assumption is that when I start the app, electron-updater parses package.json, looks at all dependencies, ensures that they are of the latest release, and starts the app. How does electron-updater know when to install updates of the application itself? Is that what `binaries` are for? However, it seems like in the examples, it is just a path to a tar archive and not to an npm. Or does it assume that the application is hosted on npm packages under the name ins the package.json and tries to check for the latest version? If that is the case, how can I see some verbose output of electron-updater? I've installed sinopia and hosted my package locally. But I do not see electron-updater checking for it or showing any errors. Is that because my application hasn't actually been installed?

**Comment by justinmchase** [comment]
It looks into the "dependencies" section of the package.json. It then looks to find them under the `node_modules` folder. If they are there and of the right version it skips them otherwise it downloads it from npm and puts it there.

**Comment by ardoramor** [comment]
Does it look at the package.json version itself and compare it with the latest available in npm? That is, if my package.json has something like

   {
      name: "package-abc",
      version: 1.2.3,
      ...
      dependencies: {
         ...
      },
      ...
   }

And npm has package-abc@1.2.4 available, will `electron-updater` download the package and make the update? I'm assuming it will follow that logic as well but it's not happening and I wonder how I can debug it.

**Comment by justinmchase** [comment]
It uses [semver](http://semver.org) version rules, or the same rules that npm uses basically.

So if you have two packages A, and B, and A depends on B like so:

```
{
  "name": "A"
  "dependencies": {
    "B": "^0.0.1"
  }
}
{
  "name": "B"
  "version": "0.0.2"
}
```

It will then use the [caret range](https://www.npmjs.com/package/semver#caret-ranges-123-025-004) `"^0.0.1"` to determine the correct version to use based on all available published versions.

> **Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4**
> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

If you specify an exact version in your `"dependencies"` section it will only pull in that exact version and never update them. If you use a version range such as `^0.0.1` or `~0.0.1` or `0.0.x`, etc. then it will trigger an update if a newer dependencies is published that matches that version specifier.

The `"devDependencies"` section is ignored for updating. The `"binaries"` section is another thing, it will allow you to pull down a platform / configuration specific payload and unzip that into the local dependency. It is an `electron-updater` specific thing.

**Comment by ardoramor** [comment]
Sorry, I think maybe I'm not expressing myself as I want.

I have my electron application, for example called `App ABC` with package name `app-abc` and version `1.2.3`. It is `npm pack`ed and `npm publish`ed to `sinopia's /packages/app-abc`.

The root of application has the following files:

- resources/
- locales/
- AppABC.exe
- ...

`resources/` directory contains `app.asar` and `atom.asar`, as well as `app.asar.unpacked/` directory with one node module that cannot be packed with `asar`. Within `app.asar` is located my application's main package.json with the following contents: 

     {
        name: 'app-abc',
        version: '1.2.3',
        dependencies: {
           vue: '^1.0.10',
        },
        ...
     }

Based on this information and from what I understood in your explanation, upon startup of the application, AppABC.exe, `electron-updater` will kick in, look into `app.asar` archive.

There it will check the version of `app-abc`, because latest version it will find matching the current one, updater will move to dependencies. It will check `vue` and see that 1.0.16 is available. Updater will download newer vue version and update the `app.asar` archive.

Let's say that I then make changes to my app, updating some views, adding new dependencies, etc. I release version `app-abc@1.3.1`.

I again start AppABC.exe, the updater checks latest version of `app-abc` on npm and find that there is a newer version available. It will then download the latest version of my app from npm and extract it into the root of the application, restarting it, correct?

I basically want to make sure that not only node modules in my `dependencies` list get updated but my latest app releases also get to my users.

**Comment by justinmchase** [comment]
Ah yes, the app itself is updated by just looking for the name and version in its own package.json. It will just always update to the latest one. After pulling down a newer version of itself it will look at its dependencies and see if there are newer dependencies needed.

**Comment by justinmchase** [comment]
And actually now that I say it, it looks at whatever release is tagged as "latest" in npm, which by default is the last thing of the highest version you publish. But you can actually change it to manually tag a release as "latest" after its published. You can configure the updater to use a different tag while debugging so you can, essentially, publish an udpate, test it locally, then tag it as latest and have users pull in the update.

**Comment by ardoramor** [comment]
Hmm, I've started to get another error. I've built my application. The built files I packed and published to local sinopia server. I then packed the built files for release with ASAR into app.asar with configuration of one node module being unpacked upon installation.

Now, when I try to run the .exe of my application, I get the following error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: ENOENT: no such file or directory, open
'C:\...\app-abc\resources\app.asar\package.json'
   at Error (native)
```

I've checked `app.asar` and it does contain package.json. When I take the same code and rebuild it without `electron-updater`, the application launches just fine. It seems like `electron-updater` is unable to access files within the ASAR archive. Did I somehow configure it incorrectly?

**Comment by justinmchase** [comment]
It may be, I haven't tried it to be honest :-X

**Comment by justinmchase** [comment]
I know you want something that is installer-less so I was reluctant to say this but this is still probably relevant:
https://github.com/EvolveLabs/electron-updater/issues/48#issuecomment-175260052

However, being that you still want to be totally portable I don't have a better suggestion for you.

**Comment by ardoramor** [comment]
Ah, I understand, this makes more sense. Thanks for the fast feedback!
