### ISSUE TITLE
Use `got`

### ISSUE THREAD

**Issue by sindresorhus** [EvolveLabs/electron-updater#7]
Instead of reinventing the wheel here, you could use [`got`](https://github.com/sindresorhus/got). It's lightweight and does exactly what you already have, and a little bit more.

https://github.com/EvolveLabs/electron-updater/blob/4df2f6a3c24d72c129653bf40b707d60044c18a8/lib/download.js

**Comment by justinmchase** [comment]
Cool, I'll check it out. Thanks :+1:
