### ISSUE TITLE
Does this require npm on the user's system?

### ISSUE THREAD

**Issue by pfraze** [EvolveLabs/electron-updater#8]
I can't find this info in the readme, and it's unclear scanning over the source:

Does this package require `npm` to be installed on the user's computer for it to work?

**Comment by justinmchase** [comment]
No it doesn't. It should be stand alone, it doesn't mimick all of the features of npm either. It only dumbly fetches code from packages. It doesn't, for example, run scripts such as "npm install" and subsequently doesn't compile native modules on the users system. It will instead download binaries that are pre-built. That should be in there now but its a bit of a work in progress still.

**Comment by pfraze** [comment]
Got it, cheers
